---
- name: install custom facts
  hosts: all
  become: true
  become_method: sudo
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: localfacts.fact
  tasks:
    - name: create fact directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: install new facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
- name: install
  hosts: all
  become: true
  tasks:
    - name: installing
      yum:
        name: "{{ ansible_local.localfacts.localfacts.package }}"
    - name: start as a service
      service:
        name: "{{ ansible_local.localfacts.localfacts.service }}"
        enabled: true
        state: started
    
